version: '3'
services:
  dev:
    image: rrhh-front:latest
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"

  prod:
    image: rrhh-front:latest
    build:
      context: .
      target: ngx
    ports:
      - "80:80"
